# районы Екатеринбурга
CALLBACK_BUTTON1_VerhIsetskiy = "callback_button1_verhisetskiy"
CALLBACK_BUTTON2_Zheleznodorozhniy = "callback_button2_zheleznodorozhniy"
CALLBACK_BUTTON3_Kirovskiy = "callback_button3_kirovskiy"
CALLBACK_BUTTON4_Leninskiy = "callback_button4_Leninskiy"
CALLBACK_BUTTON5_Oktyabrskiy = "callback_button5_oktyabrskiy"
CALLBACK_BUTTON6_Ordzhonikidzevskiy = "callback_button6_ordzhonikidzevskiy"
CALLBACK_BUTTON7_Chkalovskiy = "callback_button7_chkalovskiy"

# Верх-Исетский
CALLBACK_BUTTON_MICRORAYON_SHIROKAYARECHKA = "callback_button_shirokayarechka"
CALLBACK_BUTTON_MICRORAYON_GORAKHRUSTALNAYA = "callback_button_gorakhrustalnaya"
CALLBACK_BUTTON_MICRORAYON_LISTVENNIY = "callback_button_listvenniy"
CALLBACK_BUTTON_MICRORAYON_PEREGON = "callback_button_peregon"
CALLBACK_BUTTON_MICRORAYON_SVETLAYARECHKA = "callback_button_svetlayarechka"
CALLBACK_BUTTON_MICRORAYON_VIZ = "callback_button_viz"
CALLBACK_BUTTON_MICRORAYON_ZARECHNIY = "callback_button_zarechniy"

# Железнодорожный
CALLBACK_BUTTON_MICRORAYON_VOKZALNIY = "callback_button_vokzalniy"
CALLBACK_BUTTON_MICRORAYON_GORNOZAVODSKIY = "callback_button_gornozavodskiy"
CALLBACK_BUTTON_MICRORAYON_PALKINO = "callback_button_palkino"
CALLBACK_BUTTON_MICRORAYON_SEMKLYUCHEI = "callback_button_semklyuchei"
CALLBACK_BUTTON_MICRORAYON_STARAYASORTIROVKA = "callback_button_starayasortirovka"
CALLBACK_BUTTON_MICRORAYON_NOVAYASORTIROVKA = "callback_button_novayasortirovka"
CALLBACK_BUTTON_MICRORAYON_SORTIROVOCHNIY = "callback_button_sortirovochniy"

# Кировский
CALLBACK_BUTTON_MICRORAYON_VTUZGORODOK = "callback_button_vtuzgorodok"
CALLBACK_BUTTON_MICRORAYON_IZOPLIT = "callback_button_izoplit"
CALLBACK_BUTTON_MICRORAYON_KALINOVSKIY = "callback_button_kalinovskiy"
CALLBACK_BUTTON_MICRORAYON_KOMSOMOLSKIY = "callback_button_komsomolskiy"
CALLBACK_BUTTON_MICRORAYON_PIONERSKIY = "callback_button_pionerskiy"
CALLBACK_BUTTON_MICRORAYON_CENTRALNIY = "callback_button_centralniy"
CALLBACK_BUTTON_MICRORAYON_SHARTASH = "callback_button_shartash"

# Ленинский
CALLBACK_BUTTON_MICRORAYON_YUGOZAPADNIY = "callback_button_yugozapadniy"
CALLBACK_BUTTON_MICRORAYON_MOSKOVSKAYAGORKA = "callback_button_moskovskayagorka"
CALLBACK_BUTTON_MICRORAYON_UNC = "callback_button_unc"
CALLBACK_BUTTON_MICRORAYON_AKADEMICHESKIY = "callback_button_akademicheskiy"

# Октябрьский
CALLBACK_BUTTON_MICRORAYON_KOLTSOVO = "callback_button_koltsovo"
CALLBACK_BUTTON_MICRORAYON_KOMPRESSORNIY = "callback_button_kompressorniy"
CALLBACK_BUTTON_MICRORAYON_MALYIISTOK = "callback_button_malyiistok"
CALLBACK_BUTTON_MICRORAYON_PARKOVIY = "callback_button_parkoviy"
CALLBACK_BUTTON_MICRORAYON_SIBIRSKIY = "callback_button_sibirskiy"
CALLBACK_BUTTON_MICRORAYON_SINIEKAMNI = "callback_button_siniekamni"
CALLBACK_BUTTON_MICRORAYON_GLUBOKOE = "callback_button_glubokoe"
CALLBACK_BUTTON_MICRORAYON_MOSTOVKA = "callback_button_mostovka"
CALLBACK_BUTTON_MICRORAYON_LECHEBNIY = "callback_button_lechebniy"
CALLBACK_BUTTON_MICRORAYON_PTICEFABRIKA = "callback_button_pticefabrika"

# Орджоникидзевский
CALLBACK_BUTTON_MICRORAYON_SEVERNIYPROMYSHLENNIY = "callback_button_severniypromyshlenniy"
CALLBACK_BUTTON_MICRORAYON_URALMASH = "callback_button_uralmash"
CALLBACK_BUTTON_MICRORAYON_ELMASH = "callback_button_elmash"
CALLBACK_BUTTON_MICRORAYON_KOZLOVSKIY = "callback_button_kozlovskiy"
CALLBACK_BUTTON_MICRORAYON_APPARATNIY = "callback_button_apparatniy"
CALLBACK_BUTTON_MICRORAYON_YAGODNIY = "callback_button_yagodniy"

# Чкаловский
CALLBACK_BUTTON_MICRORAYON_BOTANICHESKIY = "callback_button_botanicheskiy"
CALLBACK_BUTTON_MICRORAYON_VTORCHERMET = "callback_button_vtorchermet"
CALLBACK_BUTTON_MICRORAYON_ELIZAVET = "callback_button_elizavet"
CALLBACK_BUTTON_MICRORAYON_NIZHNEISETSKIY = "callback_button_nizhneisetskiy"
CALLBACK_BUTTON_MICRORAYON_RUDNIY = "callback_button_rudniy"
CALLBACK_BUTTON_MICRORAYON_UKTUSSKIY = "callback_button_uktusskiy"
CALLBACK_BUTTON_MICRORAYON_KHIMMASH = "callback_button_khimmash"
CALLBACK_BUTTON_MICRORAYON_YUZHNIY = "callback_button_yuzhniy"
CALLBACK_BUTTON_MICRORAYON_PRIISKOVIY = "callback_button_priiskoviy"
CALLBACK_BUTTON_MICRORAYON_KHUTOR = "callback_button_khutor"






